### ISSUE TITLE
Issues with quantized models

### ISSUE THREAD

**Issue by looeee** [donmccurdy/glTF-Transform#260]
As far as I can see, nearly every model that I'm quantizing is reporting this warning:

`quantize: Skipping TEXCOORD_0; out of supported range.`

Then when I attempt to view the model, it loads but is invisible. 

For example, with this unprocessed model: 
[Car_csi4.zip](https://github.com/donmccurdy/glTF-Transform/files/6525948/Car_csi4.zip)

![car](https://user-images.githubusercontent.com/5307958/119217148-5c6e6700-bb02-11eb-828c-9d33e0a5c558.png)

If I run 

``` 
 gltf-transform quantize .\model.gltf .\model_quant.glb
```

This is the output:

```
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
warn: quantize: Skipping TEXCOORD_0; out of supported range.
info: model.gltf (1.39 MB) → model_quant.glb (1.06 MB)
```

And the resulting quantized model:

[model_quant.zip](https://github.com/donmccurdy/glTF-Transform/files/6525954/model_quant.zip)

![blank](https://user-images.githubusercontent.com/5307958/119217153-6728fc00-bb02-11eb-8084-421cbe3e3fa6.png)

As you can see, there are a whole load of new errors. 

If I run gltfpack on the original model all the errors are removed and it loads correctly.

**Comment by donmccurdy** [comment]
> warn: quantize: Skipping TEXCOORD_0; out of supported range.

That's a known limitation of my quantization implementation at the moment — room for improvement (it can't quantize as fully as it potentially could) but doesn't hurt anything otherwise.

> Then when I attempt to view the model, it loads but is invisible.

There was a bug (https://github.com/mrdoob/three.js/pull/21554) in three.js affecting quantized data, and I haven't got the fix deployed in my viewer yet; should be there soon. In the meantime you can test https://sandbox.babylonjs.com/ ... which also doesn't work in this case, so something else is up...

> As you can see, there are a whole load of new errors.

That's concerning .. will take a look!

**Comment by donmccurdy** [comment]
Ah the model doesn't actually have any textures, so really the TEXCOORD_0 attributes could just be dropped...  but that's just some extra bytes, and not breaking anything.

***

The errors come down to the same issue as https://github.com/donmccurdy/glTF-Transform/issues/259#issuecomment-846364403, a bunch of `"byteStride": 0` values in the model, glTF-Transform can't really read the file with those errors in place.  It'd also be good to throw out the empty accessors:

```ts
for (const accessor of document.getRoot().listAccessors()) {
	if (accessor.getCount() === 0) {
		accessor.dispose();
	}
}
```

Is the workaround for getting rid of `byteStride: 0` feasible in your script? Haven't really seen this before, not sure if gltf-transform needs to try to detect and avoid the error. With that I do get a model that seems fine:

[export-v3-quant.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/6526000/export-v3-quant.glb.zip)
<img width="700" alt="Screen Shot 2021-05-22 at 12 16 47 AM" src="https://user-images.githubusercontent.com/1848368/119218052-07dfd300-ba93-11eb-8916-7f0c483377ba.png">

Loads in babylon but is frustum-culled in my viewer; that'll be fixed soon enough though.

**Comment by looeee** [comment]
> Is the workaround for getting rid of byteStride: 0 feasible in your script?

Yep! 

That's equivalent to your suggestion here, right? 
https://github.com/donmccurdy/glTF-Transform/issues/259#issuecomment-846364403

**Comment by donmccurdy** [comment]
Same, yes!

**Comment by looeee** [comment]
Cool, that's fixed most of the errors. I think the draco errors are still occurring though. I'll run gltfpack on any models still giving errors, that seems to fix them. 

Thanks a bunch for your help, and apologies for throwing all this extra work your way on Saturday morning :)

**Comment by donmccurdy** [comment]
>  I think the draco errors are still occurring though

Between the 'byteStride' fix and cleaning up the empty accessors (https://github.com/donmccurdy/glTF-Transform/issues/259#issuecomment-846364403) it seems like Draco is working on my side now (tested with the car example) but maybe something else is different here, or it's relying on the v0.11.1 changes.. I went ahead and published v0.11.1, let me know if that doesn't resolve it!
